import type { StockSnapshot } from '@astra/contract';
import type { Adapter, AdapterContext, AdapterResult } from './types';
import {
  asArray,
  asRecord,
  browserHeaders,
  errorMessage,
  fetchWithTimeout,
  parsePriceToCents,
  rateLimitedFailure,
  readString,
} from './util';

/**
 * Structured-data adapter: parse every `<script type="application/ld+json">` block in the
 * product page and read schema.org Offer availability.
 *
 * More durable than HTML scraping (the JSON-LD block is generated by the theme's SEO layer and
 * changes far less often than markup) but less direct than the Shopify endpoints, hence third.
 *
 * PURCHASABILITY DECISION: only `InStock` counts as available.
 *   - `BackOrder` and `PreOrder` mean the item can be *ordered* but not shipped now. For a drop
 *     watcher this is the wrong signal: a store that lists the tablet as PreOrder for weeks would
 *     latch `true` once and then never produce the edge that matters.
 *   - `LimitedAvailability`, `OnlineOnly`, `SoldOut`, `OutOfStock`, `Discontinued` -> false.
 *   This is the conservative reading; erring toward `false` here costs a late alert, whereas
 *   erring toward `true` costs a permanently latched variant that can never alert again until
 *   the cooldown lapses and it flips back.
 */
const PURCHASABLE_AVAILABILITY = new Set(['instock']);

export const jsonLdAdapter: Adapter = {
  name: 'jsonld',
  async run(ctx: AdapterContext): Promise<AdapterResult> {
    let html: string;
    try {
      const res = await fetchWithTimeout(
        ctx.fetchImpl,
        ctx.productUrl,
        { method: 'GET', headers: browserHeaders('text/html,application/xhtml+xml') },
        ctx.timeoutMs,
      );
      // A 429 is about the host, not this path: sibling endpoints share the bucket.
      const throttled = rateLimitedFailure(res, ctx.productUrl);
      if (throttled !== null) return throttled;
      if (!res.ok) return { ok: false, reason: `HTTP ${res.status} from ${ctx.productUrl}` };
      html = await res.text();
    } catch (err) {
      return { ok: false, reason: `fetch failed for ${ctx.productUrl}: ${errorMessage(err)}` };
    }

    const blocks = extractLdJsonBlocks(html);
    if (blocks.length === 0) return { ok: false, reason: 'no application/ld+json blocks in HTML' };

    const nodes: Record<string, unknown>[] = [];
    for (const block of blocks) {
      let parsed: unknown;
      try {
        parsed = JSON.parse(block);
      } catch {
        continue; // One malformed block must not sink the others.
      }
      collectNodes(parsed, nodes);
    }

    const snapshots: StockSnapshot[] = [];
    const seen = new Set<string>();
    for (const node of nodes) {
      if (!typeIncludes(node['@type'], 'Product')) continue;
      const productName = readString(node['name']);
      const offers = expandOffers(node['offers']);
      offers.forEach((offer, index) => {
        const snapshot = parseOffer(offer, productName, index, ctx.now);
        if (snapshot === null || seen.has(snapshot.variantId)) return;
        seen.add(snapshot.variantId);
        snapshots.push(snapshot);
      });
    }

    if (snapshots.length === 0) {
      return { ok: false, reason: 'no Product/Offer nodes with a readable availability' };
    }
    return { ok: true, snapshots };
  },
};

/** Case-insensitive, attribute-order-tolerant extraction of ld+json script bodies. */
export function extractLdJsonBlocks(html: string): string[] {
  const blocks: string[] = [];
  const re = /<script\b[^>]*type\s*=\s*["']?application\/ld\+json["']?[^>]*>([\s\S]*?)<\/script\s*>/gi;
  let match: RegExpExecArray | null;
  while ((match = re.exec(html)) !== null) {
    const body = match[1];
    if (body !== undefined && body.trim() !== '') blocks.push(body.trim());
  }
  return blocks;
}

/** Flatten arrays, `@graph` wrappers and arbitrary nesting into a list of objects. */
function collectNodes(value: unknown, out: Record<string, unknown>[]): void {
  const arr = asArray(value);
  if (arr !== null) {
    for (const item of arr) collectNodes(item, out);
    return;
  }
  const record = asRecord(value);
  if (record === null) return;
  out.push(record);
  for (const key of Object.keys(record)) {
    const child = record[key];
    if (typeof child === 'object' && child !== null) collectNodes(child, out);
  }
}

function typeIncludes(value: unknown, wanted: string): boolean {
  const target = wanted.toLowerCase();
  const single = readString(value);
  if (single !== null) return single.toLowerCase().endsWith(target);
  const arr = asArray(value);
  if (arr === null) return false;
  return arr.some((entry) => {
    const s = readString(entry);
    return s !== null && s.toLowerCase().endsWith(target);
  });
}

/** Accepts a single Offer, an array of Offers, or an AggregateOffer wrapping either. */
function expandOffers(value: unknown): Record<string, unknown>[] {
  const out: Record<string, unknown>[] = [];
  const push = (candidate: unknown): void => {
    const record = asRecord(candidate);
    if (record === null) return;
    if (typeIncludes(record['@type'], 'AggregateOffer')) {
      const nested = record['offers'];
      if (nested === undefined) return;
      out.push(...expandOffers(nested));
      return;
    }
    out.push(record);
  };

  const arr = asArray(value);
  if (arr !== null) {
    for (const item of arr) push(item);
    return out;
  }
  push(value);
  return out;
}

function parseOffer(
  offer: Record<string, unknown>,
  productName: string | null,
  index: number,
  now: number,
): StockSnapshot | null {
  const availabilityRaw = readAvailability(offer);
  if (availabilityRaw === null) return null;
  const available = PURCHASABLE_AVAILABILITY.has(availabilityRaw);

  const item = asRecord(offer['itemOffered']);
  const sku =
    readString(offer['sku']) ??
    readString(offer['mpn']) ??
    (item !== null ? readString(item['sku']) : null) ??
    readString(offer['@id']) ??
    null;

  const variantId = sku ?? `${slugify(productName ?? 'product')}-offer-${index}`;
  const title =
    readString(offer['name']) ??
    (item !== null ? readString(item['name']) : null) ??
    productName ??
    `Offer ${index + 1}`;

  const priceSpec = asRecord(offer['priceSpecification']);
  const priceCents =
    parsePriceToCents(offer['price']) ??
    (priceSpec !== null ? parsePriceToCents(priceSpec['price']) : null);
  const currency =
    readString(offer['priceCurrency']) ??
    (priceSpec !== null ? readString(priceSpec['priceCurrency']) : null);

  return { variantId, title, available, priceCents, currency, checkedAt: now };
}

/** `https://schema.org/InStock` | `InStock` | `{"@id": "...InStock"}` -> `instock`. */
function readAvailability(offer: Record<string, unknown>): string | null {
  const candidates: unknown[] = [offer['availability'], offer['itemAvailability']];
  for (const candidate of candidates) {
    const direct = readString(candidate);
    const record = asRecord(candidate);
    const raw = direct ?? (record !== null ? readString(record['@id']) : null);
    if (raw === null) continue;
    const tail = raw.split(/[/#]/).pop();
    if (tail === undefined || tail === '') continue;
    return tail.toLowerCase();
  }
  return null;
}

function slugify(input: string): string {
  return (
    input
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'product'
  );
}
